apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lwwebapp1
spec:
  project: default
  destination:
    server: https://192.168.229.157:8443
    namespace: default
  source:
    repoURL: https://github.com/KabraJiii/session-6-argocd.git
    path: prod
    targetRevision: main
