apiVersion: v1
kind: Secret
metadata:
  name: external-lwc2
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: external-lwc2-cluster
  server: https://192.168.229.157:8443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImZFeHBuWTFneXA3bEpKbVZtR196Q2tXdmZkVWdUSnlLSGI3bUV0OU1mX1kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0MDIxNDA2LCJpYXQiOjE3NDQwMTc4MDYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMzJmMTBiYjgtY2M5ZC00NTdhLWI4MjAtMmVkNzdlZjI4ZWRlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb2RzYSIsInVpZCI6IjNkYzExOTVjLWNjNDAtNDhhZi1hMzI4LWM1NDYwNjY1ZjMzZCJ9fSwibmJmIjoxNzQ0MDE3ODA2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpwcm9kc2EifQ.bjL5viELQ6Tvlq0OgMvof72I_MpDn3DdFZSBKfCLCJaeAOg1qlSIYlnTrAqjig9Nf5Sjzq2I30SixIr90Rr7LJ-zXZnfH3fu6hopPT_kgZ13ze2g79W1PLRpBo-6STqpwXjUb2UCg4IOsRh6KGvKAuC-YUHFo14S5VJATK9jatJkc5mjycfdiri-mEoZs3nCyZ966jdKSOcfo9X4bf0C7a4vCT-4RwSWbFaf1bvzRnWwbSoTHmc4Lxg3JB3Px0Qrv3lLL0IfVADse2XZPR1HzGSzN-1uVTssJ09ixC3smr2ZaOYGGTCxoH2BQSiGpvMpL0ipk1FrNBjnMuhdbVRiWA",
      "tlsClientConfig":
        "insecure": true
        }
    }
