apiVersion: v1
kind: Secret
metadata:
  name: external-lwc2
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: external-lwc2-cluster
  server: https://192.168.229.157:8443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImZFeHBuWTFneXA3bEpKbVZtR196Q2tXdmZkVWdUSnlLSGI3bUV0OU1mX1kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ0MDEzMzUwLCJpYXQiOjE3NDQwMDk3NTAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZTBlYTc2ZjUtY2U0YS00ZjhjLWE0MDAtZDY2ZDI2ZmExYzdiIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb2RzYSIsInVpZCI6IjNkYzExOTVjLWNjNDAtNDhhZi1hMzI4LWM1NDYwNjY1ZjMzZCJ9fSwibmJmIjoxNzQ0MDA5NzUwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpwcm9kc2EifQ.fDzlOWxh_0ZmRVLMZzBKY_F4I7yTBdUSXt6WFtv5bmMqFTcnmrjWikdBAI_Zq4dX2gR9pFsOIEnn3SXdemSx1i5D86IFA5RjN9Sd1zO2Zt2-P35y3wEY6bwLe0RQM_uYb0GhsOFydMb1PjdaVen4Ne1zNHr8_8tO04_d82xIivdOJdJ7tshZsRr3chSXKVv7jPxhCJ978I-Q2xq2fqGJ1uPwLaMf5knVSHQzOKDUf3aDEn0L10owyIDlPUjJ6EsDwjqDPIwDowN-oRQ25sSuWvrz50yK8CcctcQZfRAqJUHcw7zHx3N5QWyRGOI_KL4U0Vx7MvmPMRaypSFYF78Gnw",
      "tlsClientCOnfig":
          {
            "insecure": true
          }
    }

